apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  selector:
    matchLabels:
      app: my-react-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: asia.gcr.io/project-punyakon/react-image:v0.1.50
          ports:
            - containerPort: 4173
      imagePullSecrets:
        - name: gcr-io
