apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: my-react-app
  ports:
    - port: 4173
      protocol: TCP
      targetPort: 4173
      nodePort: 30800
